apiVersion: v1
data:
  client-passwords: ME5RZVdFN3ZDOQ==
  controller-password: MjFoVk9QUzVCbw==
  inter-broker-password: MjFoVk9QUzVCbw==
  zookeeper-password: MjFoVk9QUzVCbw==
kind: Secret
metadata:
  name: lab-secrets
  namespace: kafka-zk
type: Opaque
