apiVersion: v1
kind: Service
metadata:
  name: "{{ include "kafka-lab.fullname" . }}-ext-l4-1"
  labels:
    {{- include "kafka-lab.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: ingress-192.168.100.111
    metallb.universe.tf/loadBalancerIPs: 192.168.100.111
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-client
    port: 9095
    protocol: TCP
    targetPort: external
  selector:
    app.kubernetes.io/instance: {{ include "kafka-lab.fullname" . }}
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: kafka
    statefulset.kubernetes.io/pod-name: kafka-lab-zkmode-broker-0
