apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: homelab
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/dmilet/homelab-deployments'
  - 'registry-1.docker.io/davidmilet'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: homelab
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: prod
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/dmilet/homelab-deployments'
  - 'registry-1.docker.io/davidmilet'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: prod
    server: https://kubernetes.default.svc
