name: Bump up release number

on: workflow_dispatch

env:
  RELEASE_ID: 0.0.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "### last comment" >> .github/workflows/bump_up_release.yml
    - name: Commit to new branch
      uses: devops-infra/action-commit-push@master
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        add_timestamp: false
        commit_prefix: "[AUTO]"
        commit_message: "Automatic commit"
        force: true
        target_branch: "release/${{ env.RELEASE_ID }}"
