name: Docker Image CI Frontend - Flask App

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'apps/frontends/flaskapp/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'apps/frontends/flaskapp/**'


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - uses: microsoft/action-python@0.7.2
    #   with:
    #     root: apps/frontends/flaskapp
    #     pylint: true
        
    #- name: Build the Docker image
    #  run: docker build apps/frontends/flaskapp --file apps/frontends/flaskapp/Dockerfile --tag davidmilet/homelab:frontends-flaskappp-$(date +%s)
    - uses: docker/login-action@v3.1.0
      with:
        username: "${{ secrets.DOCKERHUB_USERNAME }}"
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
    - run: |
         grep RELEASE_ID apps/frontends/flaskapp/properties.sh >> $GITHUB_ENV
    - uses: docker/build-push-action@v5.3.0
      with:
        context: apps/frontends/flaskapp
        file: apps/frontends/flaskapp/Dockerfile
        tags: "davidmilet/homelab:frontends-flaskappp-${{ env.RELEASE_ID }}"
        push: true


  deploy:
    runs-on: ubuntu-latest
    needs: build
    # deploy only if built from main branch
    if: github.ref == 'refs/heads/main'
    steps:    
    # - uses: actions/checkout@v4
    # - run: |
    #      grep RELEASE_ID apps/frontends/flaskapp/properties.sh >> $GITHUB_ENV

    - run: echo "Release ID = ${{ env.RELEASE_ID }}"

    # update helm chart 
    - uses: actions/checkout@v4
      with:
        repository: 'https://github.com/dmilet/homelab-deployments.git'
        ref: 'refs/heads/main'
        # Default: ${{ github.token }}
        #token: '${{ secrets.GITHUB_RW_TOKEN }} '
        # Relative path under $GITHUB_WORKSPACE to place the repository
        #path: 'homelab-deployments'

    - run: cat values/homelab/frontend.yaml
    - run: sed "s/frontends-flaskappp-.*$/frontends-flaskappp-${{ env.RELEASE_ID }}/g" values/homelab/frontend.yaml
