name: Docker Image CI Frontend - Flask App

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'apps/frontends/flaskapp/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'apps/frontends/flaskapp/**'


jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_ID: "${{ env.RELEASE_ID }}"
    steps:
    - uses: actions/checkout@v4
    # - uses: microsoft/action-python@0.7.2
    #   with:
    #     root: apps/frontends/flaskapp
    #     pylint: true
        
    #- name: Build the Docker image
    #  run: docker build apps/frontends/flaskapp --file apps/frontends/flaskapp/Dockerfile --tag davidmilet/homelab:frontends-flaskappp-$(date +%s)
    - uses: docker/login-action@v3.1.0
      with:
        username: "${{ secrets.DOCKERHUB_USERNAME }}"
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
    - name: Retrieve RELEASE_ID
      run: |
         grep RELEASE_ID apps/frontends/flaskapp/properties.sh >> $GITHUB_ENV
    - uses: docker/build-push-action@v5.3.0
      with:
        context: apps/frontends/flaskapp
        file: apps/frontends/flaskapp/Dockerfile
        tags: "davidmilet/homelab:frontends-flaskappp-${{ env.RELEASE_ID }}"
        push: true


  deploy:
    runs-on: ubuntu-latest
    needs: build
    # deploy only if built from main branch
    if: github.ref == 'refs/heads/main'
    steps:    
    # - uses: actions/checkout@v4
    # - run: |
    #       grep RELEASE_ID apps/frontends/flaskapp/properties.sh >> $GITHUB_ENV

    - name: Show RELEASE_ID
      run: echo "Release ID = ${{ needs.build.outputs.RELEASE_ID }}"

    # update helm chart 
    - uses: actions/checkout@v4
      with:
        repository: dmilet/homelab-deployments
        ref: refs/heads/main
        # Default: ${{ github.token }}
        token: '${{ secrets.HOMELAB_ACTIONS_RW }}'
        # Relative path under $GITHUB_WORKSPACE to place the repository
        #path: 'homelab-deployments'


    - name: update values files for new RELEASE_ID
      run: sed -i "s/frontends-flaskappp-.*$/frontends-flaskappp-${{ needs.build.outputs.RELEASE_ID }}/g" values/homelab/frontend.yaml

    - name: confirm change done
      run: cat values/homelab/frontend.yaml

    - name: Commit to new branch and push
      run: |
        git config --global user.email "david.milet@gmail.com"
        git config --global user.name "David Milet"
        git checkout -b release/${{ needs.build.outputs.RELEASE_ID }}
        git add .
        git commit -m "Release ${{ needs.build.outputs.RELEASE_ID }}"
        git push origin release/${{ needs.build.outputs.RELEASE_ID }}

    # - name: Commit to new branch
    #   uses: devops-infra/action-commit-push@master
    #   with:
    #     github_token: ${{ github.token }}
    #     add_timestamp: false
    #     commit_prefix: "[AUTO]"
    #     commit_message: "Release ${{ needs.build.outputs.RELEASE_ID }}"
    #     force: true
    #     target_branch: "release/${{ needs.build.outputs.RELEASE_ID }}"
    # - name: Create pull request
    #   uses: devops-infra/action-pull-request@master
    #   with:
    #     github_token: ${{ github.token }}
    #     body: "**Automated pull request**<br><br>Replaced foo/bar"
    #     title: ${{ github.event.commits[0].message }}
    #     source_branch: "release/${{ needs.build.outputs.RELEASE_ID }}"
    #     target_branch: main
