name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file apps/frontends/flaskapp/Dockerfile --tag davidmilet/homelab:frontends-flaskappp-$(date +%s)
    - uses: docker/build-push-action@v5.3.0
      with:
        file: apps/frontends/flaskapp/Dockerfile
        tags: "davidmilet/homelab:frontends-flaskappp-$(date +%s)"
        push: true
