name: Docker Image CI Frontend - Flask App

on:
  push:
    branches: 
      - main
    paths:
      - apps/frontends/flaskapp
  pull_request:
    branches: 
      - main
    paths:
      - apps/frontends/flaskapp

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/action-python@0.7.2
      with:
        root: apps/frontends/flaskapp
        pylint: true
        
    #- name: Build the Docker image
    #  run: docker build apps/frontends/flaskapp --file apps/frontends/flaskapp/Dockerfile --tag davidmilet/homelab:frontends-flaskappp-$(date +%s)
    - uses: docker/login-action@v3.1.0
      with:
        username: "${{ secrets.DOCKERHUB_USERNAME }}"
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
    - uses: docker/build-push-action@v5.3.0
      with:
        context: apps/frontends/flaskapp
        file: apps/frontends/flaskapp/Dockerfile
        tags: "davidmilet/homelab:frontends-flaskappp-0.0.1"
        push: true
