kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: microk8s-custom-hostpath-pvc
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /pvc
volumeBindingMode: WaitForFirstConsumer